### ISSUE TITLE
Create a Fragment > Category > Listing Page

### ISSUE THREAD

**Issue by danarbello** [danarbello/astro-portfolio#22]
## Description

As a site owner, I would like to be able to auto-generate a `/fragments/${fragment.category.TERM}` view. This series of pages would queue up all fragment nodes tagged by the same `category`.

And example usage would be to list all projects (fragment nodes) that I'd completed while at MICA or in London (Central St Martins), while working at TAG, etc.

## Expected Results

- Any time a Fragment is created a content editor can supply the frontmatter with a `category` term (e.g., `Maryland Institute College of Art`, `Third & Grove`, `2003`, etc.) array
- Astro then generates a URL (e.g., `/fragments/maryland-institute-college-of-art`, `/fragments/third-and-grove`, `fragments/2003`, etc.)
- A content editor can customize some elements of the page contents:
  - Page Title (the rendered `h1` in a hero element, serve as metadata)
  - Page Description (rendered below ☝ `h1`, serve as metadata)
  - Featured Image (rendered with ☝, serve as metadata)

## Dataset

```yaml
metadata:
  - title
  - description
  - image
date: 2006-01-04
type:
  - print
  - digital
  - branding
  - writing
  - art
  - illustration
who:
  - 'Chromatic'
  - 'Chemistry'
  - 'Third & Grove'
  - '3PC Media'
  - 'Flat'
  - 'Levine & Assoc.'
  - 'Maryland Institute College of Art'
  - 'Central Saint Martins'
  - 'Self'
images:
  - ''
```

## Tasks
- [ ] TK
